create extension if not exists pgcrypto;

drop function if exists ww_reset_room(text, uuid);
drop function if exists ww_finish_room(text, uuid);
drop function if exists ww_bot_vote(text, uuid);
drop function if exists ww_vote(text, uuid, uuid);
drop function if exists ww_start_round(text, uuid);
drop function if exists ww_add_bot(text, uuid);
drop function if exists ww_join_room(text, text);
drop function if exists ww_create_room(text);
drop function if exists ww_get_room_state(text, uuid);
drop function if exists ww_random_code(integer);
drop function if exists ww_player_count(jsonb);
drop function if exists ww_has_player(jsonb, uuid);
drop function if exists ww_player_name(jsonb, uuid);

do $$
begin
  if exists (select 1 from pg_type where typname = 'ww_rooms') then
    execute 'drop function if exists ww_room_state(ww_rooms, uuid)';
  end if;
end;
$$;

drop table if exists ww_rooms;
drop table if exists ww_word_pairs;

create table ww_word_pairs (
  id bigint generated by default as identity primary key,
  villager text not null,
  wolf text not null,
  category text not null,
  constraint ww_word_pairs_unique unique (villager, wolf, category)
);

create table ww_rooms (
  code text primary key,
  host_id uuid not null,
  phase text not null default 'lobby' check (phase in ('lobby', 'discussion', 'result')),
  round integer not null default 0,
  settings jsonb not null default '{"discussionSeconds": 180, "wolfCount": 1}'::jsonb,
  players jsonb not null default '[]'::jsonb,
  current_game jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table ww_word_pairs enable row level security;
alter table ww_rooms enable row level security;

create or replace function ww_random_code(length integer default 5)
returns text
language plpgsql
as $$
declare
  alphabet text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  code text := '';
  i integer;
begin
  for i in 1..length loop
    code := code || substr(alphabet, floor(random() * length(alphabet) + 1)::integer, 1);
  end loop;
  return code;
end;
$$;

create or replace function ww_player_count(players jsonb)
returns integer
language sql
stable
as $$
  select coalesce(jsonb_array_length(players), 0);
$$;

create or replace function ww_has_player(players jsonb, player_id uuid)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from jsonb_array_elements(players) as player
    where player->>'id' = player_id::text
  );
$$;

create or replace function ww_player_name(players jsonb, player_id uuid)
returns text
language sql
stable
as $$
  select player->>'name'
  from jsonb_array_elements(players) as player
  where player->>'id' = player_id::text
  limit 1;
$$;

create or replace function ww_room_state(room ww_rooms, viewer_id uuid)
returns jsonb
language plpgsql
stable
as $$
declare
  game jsonb := room.current_game;
  player jsonb;
  players_json jsonb := '[]'::jsonb;
  viewer_assignment jsonb;
begin
  for player in select * from jsonb_array_elements(room.players) loop
    players_json := players_json || jsonb_build_array(
      jsonb_build_object(
        'id', player->>'id',
        'name', player->>'name',
        'connected', coalesce((player->>'connected')::boolean, true),
        'isBot', coalesce((player->>'bot')::boolean, false),
        'votedFor', coalesce(game->'votes' ? (player->>'id'), false)
      )
    );
  end loop;

  if game is not null and viewer_id is not null then
    viewer_assignment := game->'assignments'->(viewer_id::text);
  end if;

  return jsonb_build_object(
    'code', room.code,
    'hostId', room.host_id::text,
    'phase', room.phase,
    'round', room.round,
    'settings', room.settings,
    'players', players_json,
    'currentGame',
      case
        when game is null then null
        else jsonb_build_object(
          'category', game->'pair'->>'category',
          'startedAt', (game->>'startedAt')::bigint,
          'discussionEndsAt', (game->>'discussionEndsAt')::bigint,
          'votes', coalesce(game->'votes', '{}'::jsonb),
          'result', game->'result',
          'viewerWord', viewer_assignment->>'word',
          'viewerRole', viewer_assignment->>'role'
        )
      end
  );
end;
$$;

create or replace function ww_get_room_state(p_code text, p_player_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  room ww_rooms;
begin
  select * into room from ww_rooms where code = upper(trim(p_code));
  if not found then
    raise exception '방을 찾을 수 없어요.';
  end if;
  return ww_room_state(room, p_player_id);
end;
$$;

create or replace function ww_create_room(p_name text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  room_code text;
  player_id uuid := gen_random_uuid();
  clean_name text := left(trim(p_name), 16);
  room ww_rooms;
begin
  if clean_name = '' then
    raise exception '아이디를 입력해주세요.';
  end if;

  loop
    room_code := ww_random_code(5);
    exit when not exists (select 1 from ww_rooms where code = room_code);
  end loop;

  insert into ww_rooms (code, host_id, players)
  values (
    room_code,
    player_id,
    jsonb_build_array(jsonb_build_object('id', player_id::text, 'name', clean_name, 'connected', true))
  )
  returning * into room;

  return jsonb_build_object('playerId', player_id::text, 'room', ww_room_state(room, player_id));
end;
$$;

create or replace function ww_join_room(p_code text, p_name text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  room ww_rooms;
  player_id uuid := gen_random_uuid();
  clean_name text := left(trim(p_name), 16);
begin
  if clean_name = '' then
    raise exception '아이디를 입력해주세요.';
  end if;

  select * into room from ww_rooms where code = upper(trim(p_code)) for update;
  if not found then
    raise exception '방을 찾을 수 없어요.';
  end if;
  if room.phase <> 'lobby' then
    raise exception '진행 중인 방에는 입장할 수 없어요.';
  end if;
  if exists (select 1 from jsonb_array_elements(room.players) as player where player->>'name' = clean_name) then
    raise exception '이미 사용 중인 아이디예요.';
  end if;

  update ww_rooms
  set
    players = room.players || jsonb_build_array(jsonb_build_object('id', player_id::text, 'name', clean_name, 'connected', true)),
    updated_at = now()
  where code = room.code
  returning * into room;

  return jsonb_build_object('playerId', player_id::text, 'room', ww_room_state(room, player_id));
end;
$$;

create or replace function ww_add_bot(p_code text, p_player_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  room ww_rooms;
  bot_id uuid := gen_random_uuid();
  bot_index integer := 1;
  bot_name text;
begin
  select * into room from ww_rooms where code = upper(trim(p_code)) for update;
  if not found then
    raise exception '방을 찾을 수 없어요.';
  end if;
  if room.host_id <> p_player_id then
    raise exception '방장만 AI를 추가할 수 있어요.';
  end if;
  if room.phase <> 'lobby' then
    raise exception '대기실에서만 AI를 추가할 수 있어요.';
  end if;
  if ww_player_count(room.players) >= 10 then
    raise exception '플레이어는 최대 10명까지 가능해요.';
  end if;

  loop
    bot_name := 'AI ' || bot_index;
    exit when not exists (
      select 1 from jsonb_array_elements(room.players) as player where player->>'name' = bot_name
    );
    bot_index := bot_index + 1;
  end loop;

  update ww_rooms
  set
    players = room.players || jsonb_build_array(
      jsonb_build_object('id', bot_id::text, 'name', bot_name, 'connected', true, 'bot', true)
    ),
    updated_at = now()
  where code = room.code
  returning * into room;

  return ww_room_state(room, p_player_id);
end;
$$;

create or replace function ww_start_round(p_code text, p_player_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  room ww_rooms;
  pair ww_word_pairs;
  wolf_count integer;
  player_count integer;
  wolf_ids text[];
  player jsonb;
  assignments jsonb := '{}'::jsonb;
  is_wolf boolean;
  now_ms bigint := floor(extract(epoch from clock_timestamp()) * 1000);
begin
  select * into room from ww_rooms where code = upper(trim(p_code)) for update;
  if not found then
    raise exception '방을 찾을 수 없어요.';
  end if;
  if room.host_id <> p_player_id then
    raise exception '방장만 게임을 시작할 수 있어요.';
  end if;

  player_count := ww_player_count(room.players);
  if player_count < 3 then
    raise exception '워드울프는 최소 3명이 필요해요.';
  end if;

  select * into pair from ww_word_pairs order by random() limit 1;
  wolf_count := least(coalesce((room.settings->>'wolfCount')::integer, 1), greatest(1, player_count - 2));

  select array_agg(player_id)
  into wolf_ids
  from (
    select player->>'id' as player_id
    from jsonb_array_elements(room.players) as player
    order by random()
    limit wolf_count
  ) picked;

  for player in select * from jsonb_array_elements(room.players) loop
    is_wolf := (player->>'id') = any(wolf_ids);
    assignments := jsonb_set(
      assignments,
      array[player->>'id'],
      jsonb_build_object(
        'role', case when is_wolf then 'wolf' else 'villager' end,
        'word', case when is_wolf then pair.wolf else pair.villager end
      ),
      true
    );
  end loop;

  update ww_rooms
  set
    phase = 'discussion',
    round = room.round + 1,
    current_game = jsonb_build_object(
      'pair', jsonb_build_object('villager', pair.villager, 'wolf', pair.wolf, 'category', pair.category),
      'wolfIds', to_jsonb(wolf_ids),
      'assignments', assignments,
      'votes', '{}'::jsonb,
      'startedAt', now_ms,
      'discussionEndsAt', now_ms + coalesce((room.settings->>'discussionSeconds')::integer, 180) * 1000,
      'result', null
    ),
    updated_at = now()
  where code = room.code
  returning * into room;

  return ww_room_state(room, p_player_id);
end;
$$;

create or replace function ww_vote(p_code text, p_player_id uuid, p_target_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  room ww_rooms;
  votes jsonb;
  player_count integer;
begin
  select * into room from ww_rooms where code = upper(trim(p_code)) for update;
  if not found then
    raise exception '방을 찾을 수 없어요.';
  end if;
  if room.phase <> 'discussion' or room.current_game is null then
    raise exception '지금은 투표할 수 없어요.';
  end if;
  if not ww_has_player(room.players, p_player_id) or not ww_has_player(room.players, p_target_id) then
    raise exception '투표 대상을 확인할 수 없어요.';
  end if;
  if p_player_id = p_target_id then
    raise exception '자기 자신에게는 투표할 수 없어요.';
  end if;

  votes := jsonb_set(coalesce(room.current_game->'votes', '{}'::jsonb), array[p_player_id::text], to_jsonb(p_target_id::text), true);
  player_count := ww_player_count(room.players);

  update ww_rooms
  set
    current_game = jsonb_set(room.current_game, '{votes}', votes, true),
    updated_at = now()
  where code = room.code
  returning * into room;

  if (select count(*) from jsonb_each_text(votes)) >= player_count then
    perform ww_finish_room(p_code, room.host_id);
    select * into room from ww_rooms where code = upper(trim(p_code));
  end if;

  return ww_room_state(room, p_player_id);
end;
$$;

create or replace function ww_bot_vote(p_code text, p_player_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  room ww_rooms;
  bot jsonb;
  target_id text;
  votes jsonb;
  player_count integer;
begin
  select * into room from ww_rooms where code = upper(trim(p_code)) for update;
  if not found then
    raise exception '방을 찾을 수 없어요.';
  end if;
  if room.host_id <> p_player_id then
    raise exception '방장만 AI 투표를 실행할 수 있어요.';
  end if;
  if room.phase <> 'discussion' or room.current_game is null then
    raise exception '지금은 AI 투표를 실행할 수 없어요.';
  end if;

  votes := coalesce(room.current_game->'votes', '{}'::jsonb);

  for bot in
    select *
    from jsonb_array_elements(room.players) as player
    where coalesce((player->>'bot')::boolean, false)
      and not (votes ? (player->>'id'))
  loop
    select player->>'id'
    into target_id
    from jsonb_array_elements(room.players) as player
    where player->>'id' <> bot->>'id'
    order by random()
    limit 1;

    if target_id is not null then
      votes := jsonb_set(votes, array[bot->>'id'], to_jsonb(target_id), true);
    end if;
  end loop;

  player_count := ww_player_count(room.players);

  update ww_rooms
  set
    current_game = jsonb_set(room.current_game, '{votes}', votes, true),
    updated_at = now()
  where code = room.code
  returning * into room;

  if (select count(*) from jsonb_each_text(votes)) >= player_count then
    perform ww_finish_room(p_code, room.host_id);
    select * into room from ww_rooms where code = upper(trim(p_code));
  end if;

  return ww_room_state(room, p_player_id);
end;
$$;

create or replace function ww_finish_room(p_code text, p_player_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  room ww_rooms;
  top_score integer := 0;
  top_count integer := 0;
  eliminated_id text;
  wolf_ids text[];
  villagers_win boolean := false;
  result jsonb;
begin
  select * into room from ww_rooms where code = upper(trim(p_code)) for update;
  if not found then
    raise exception '방을 찾을 수 없어요.';
  end if;
  if room.host_id <> p_player_id then
    raise exception '방장만 결과를 열 수 있어요.';
  end if;
  if room.current_game is null then
    raise exception '진행 중인 게임이 없어요.';
  end if;

  select target, score
  into eliminated_id, top_score
  from (
    select value as target, count(*)::integer as score
    from jsonb_each_text(coalesce(room.current_game->'votes', '{}'::jsonb))
    group by value
    order by score desc
    limit 1
  ) ranked;

  if top_score is null then
    eliminated_id := null;
  else
    select count(*)
    into top_count
    from (
      select value as target, count(*)::integer as score
      from jsonb_each_text(coalesce(room.current_game->'votes', '{}'::jsonb))
      group by value
    ) scores
    where score = top_score;

    if top_count <> 1 then
      eliminated_id := null;
    end if;
  end if;

  select array_agg(value::text)
  into wolf_ids
  from jsonb_array_elements_text(room.current_game->'wolfIds');

  villagers_win := eliminated_id is not null and eliminated_id = any(wolf_ids);
  result := jsonb_build_object(
    'eliminatedId', eliminated_id,
    'tie', eliminated_id is null,
    'winners', case when villagers_win then 'villagers' else 'wolves' end,
    'words', jsonb_build_object(
      'villager', room.current_game->'pair'->>'villager',
      'wolf', room.current_game->'pair'->>'wolf'
    ),
    'wolves', to_jsonb(wolf_ids)
  );

  update ww_rooms
  set
    phase = 'result',
    current_game = jsonb_set(room.current_game, '{result}', result, true),
    updated_at = now()
  where code = room.code
  returning * into room;

  return ww_room_state(room, p_player_id);
end;
$$;

create or replace function ww_reset_room(p_code text, p_player_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  room ww_rooms;
begin
  select * into room from ww_rooms where code = upper(trim(p_code)) for update;
  if not found then
    raise exception '방을 찾을 수 없어요.';
  end if;
  if room.host_id <> p_player_id then
    raise exception '방장만 다음 판을 준비할 수 있어요.';
  end if;

  update ww_rooms
  set
    phase = 'lobby',
    current_game = null,
    updated_at = now()
  where code = room.code
  returning * into room;

  return ww_room_state(room, p_player_id);
end;
$$;

grant execute on function ww_create_room(text) to anon;
grant execute on function ww_join_room(text, text) to anon;
grant execute on function ww_get_room_state(text, uuid) to anon;
grant execute on function ww_add_bot(text, uuid) to anon;
grant execute on function ww_start_round(text, uuid) to anon;
grant execute on function ww_vote(text, uuid, uuid) to anon;
grant execute on function ww_bot_vote(text, uuid) to anon;
grant execute on function ww_finish_room(text, uuid) to anon;
grant execute on function ww_reset_room(text, uuid) to anon;
