create table if not exists ww_messages (
  id bigint generated by default as identity primary key,
  room_code text not null references ww_rooms(code) on delete cascade,
  player_id uuid not null,
  body text not null check (char_length(body) between 1 and 120),
  created_at timestamptz not null default now()
);

create index if not exists ww_messages_room_created_idx
on ww_messages (room_code, created_at desc);

alter table ww_messages enable row level security;

create or replace function ww_get_messages(p_code text, p_player_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  room ww_rooms;
begin
  select * into room from ww_rooms where code = upper(trim(p_code));
  if not found then
    raise exception '방을 찾을 수 없어요.';
  end if;
  if not ww_has_player(room.players, p_player_id) then
    raise exception '채팅을 볼 권한이 없어요.';
  end if;

  return coalesce(
    (
      select jsonb_agg(
        jsonb_build_object(
          'id', msg.id,
          'playerId', msg.player_id::text,
          'playerName', ww_player_name(room.players, msg.player_id),
          'body', msg.body,
          'createdAt', floor(extract(epoch from msg.created_at) * 1000)::bigint
        )
        order by msg.created_at asc, msg.id asc
      )
      from (
        select *
        from ww_messages
        where room_code = room.code
        order by created_at desc, id desc
        limit 80
      ) msg
    ),
    '[]'::jsonb
  );
end;
$$;

create or replace function ww_send_message(p_code text, p_player_id uuid, p_body text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  room ww_rooms;
  clean_body text := left(trim(p_body), 120);
begin
  if clean_body = '' then
    raise exception '메시지를 입력해주세요.';
  end if;

  select * into room from ww_rooms where code = upper(trim(p_code));
  if not found then
    raise exception '방을 찾을 수 없어요.';
  end if;
  if not ww_has_player(room.players, p_player_id) then
    raise exception '채팅을 보낼 권한이 없어요.';
  end if;

  insert into ww_messages (room_code, player_id, body)
  values (room.code, p_player_id, clean_body);

  return ww_get_messages(room.code, p_player_id);
end;
$$;

grant execute on function ww_get_messages(text, uuid) to anon;
grant execute on function ww_send_message(text, uuid, text) to anon;
