create table if not exists ww_word_pair_history (
  id bigint generated by default as identity primary key,
  word_pair_id bigint not null references ww_word_pairs(id) on delete cascade,
  room_code text,
  used_at timestamptz not null default now()
);

create index if not exists ww_word_pair_history_used_idx
on ww_word_pair_history (used_at desc);

alter table ww_word_pair_history enable row level security;

create or replace function ww_pick_word_pair()
returns ww_word_pairs
language plpgsql
security definer
set search_path = public
as $$
declare
  pair ww_word_pairs;
begin
  select p.*
  into pair
  from ww_word_pairs p
  where p.id not in (
    select word_pair_id
    from ww_word_pair_history
    order by used_at desc
    limit 20
  )
  order by random()
  limit 1;

  if pair.id is null then
    select *
    into pair
    from ww_word_pairs
    order by random()
    limit 1;
  end if;

  return pair;
end;
$$;

create or replace function ww_start_round(p_code text, p_player_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  room ww_rooms;
  pair ww_word_pairs;
  wolf_count integer;
  player_count integer;
  not_ready_count integer;
  shuffled_ids text[];
  wolf_ids text[];
  player_json jsonb;
  assignments jsonb := '{}'::jsonb;
  turn_order jsonb := '[]'::jsonb;
  is_wolf boolean;
  now_ms bigint := floor(extract(epoch from clock_timestamp()) * 1000);
begin
  select * into room from ww_rooms where code = upper(trim(p_code)) for update;
  if not found then
    raise exception '방을 찾을 수 없어요.';
  end if;
  if room.host_id <> p_player_id then
    raise exception '방장만 게임을 시작할 수 있어요.';
  end if;

  player_count := ww_player_count(room.players);
  if player_count < 3 then
    raise exception '워드울프는 최소 3명이 필요해요.';
  end if;

  select count(*)::integer
  into not_ready_count
  from jsonb_array_elements(room.players) as player
  where player->>'id' <> room.host_id::text
    and not coalesce((player->>'bot')::boolean, false)
    and not coalesce((player->>'ready')::boolean, false);

  if not_ready_count > 0 then
    raise exception '방장 제외 모두 준비 완료해야 시작할 수 있어요.';
  end if;

  select * into pair from ww_pick_word_pair();
  if pair.id is null then
    raise exception '단어 DB가 비어 있어요. Sync Word DB 액션을 먼저 실행해주세요.';
  end if;

  insert into ww_word_pair_history (word_pair_id, room_code)
  values (pair.id, room.code);

  delete from ww_word_pair_history
  where id in (
    select id
    from ww_word_pair_history
    order by used_at desc
    offset 500
  );

  wolf_count := least(coalesce((room.settings->>'wolfCount')::integer, 1), greatest(1, player_count - 2));

  select array_agg(player_id order by sort_key), jsonb_agg(to_jsonb(player_id) order by sort_key)
  into shuffled_ids, turn_order
  from (
    select elem->>'id' as player_id, random() as sort_key
    from jsonb_array_elements(room.players) as elem
  ) picked;

  wolf_ids := shuffled_ids[1:wolf_count];

  for player_json in select * from jsonb_array_elements(room.players) loop
    is_wolf := (player_json->>'id') = any(wolf_ids);
    assignments := jsonb_set(
      assignments,
      array[player_json->>'id'],
      jsonb_build_object(
        'role', case when is_wolf then 'wolf' else 'villager' end,
        'word', case when is_wolf then pair.wolf else pair.villager end
      ),
      true
    );
  end loop;

  update ww_rooms
  set
    phase = 'reveal',
    round = room.round + 1,
    players = (
      select coalesce(jsonb_agg(player - 'ready'), '[]'::jsonb)
      from jsonb_array_elements(room.players) as player
    ),
    current_game = jsonb_build_object(
      'pair', jsonb_build_object('villager', pair.villager, 'wolf', pair.wolf, 'category', pair.category),
      'wolfIds', to_jsonb(wolf_ids),
      'assignments', assignments,
      'turnOrder', turn_order,
      'hintIndex', 0,
      'hints', '{}'::jsonb,
      'votes', '{}'::jsonb,
      'startedAt', now_ms,
      'phaseEndsAt', now_ms + 10 * 1000,
      'activePlayerId', null,
      'result', null,
      'wolfGuess', null
    ),
    updated_at = now()
  where code = room.code
  returning * into room;

  return ww_room_state(room, p_player_id);
end;
$$;

grant execute on function ww_start_round(text, uuid) to anon;
notify pgrst, 'reload schema';
